version: "3.9"

services:
  service1:
    build:
      context: ./services/service1/
    image: "nginx-testing-service1:latest"
    container_name: "nginx-testing-service1"
    ports:
      - "4567:4567"
