version: "3.9"

networks:
  loadbalancing:
    driver: bridge

services:
  service1:
    build:
      context: ./services/service1/
    image: "nginx-testing-service1:latest"
    container_name: "nginx-testing-service1"
    ports:
      - "8001:4567"
    networks:
      - loadbalancing

  service2:
    build:
      context: ./services/service2/
    image: "nginx-testing-service2:latest"
    container_name: "nginx-testing-service2"
    ports:
      - "8002:4567"
    networks:
      - loadbalancing

  service3:
    build:
      context: ./services/service3/
    image: "nginx-testing-service3:latest"
    container_name: "nginx-testing-service3"
    ports:
      - "8003:4567"
    networks:
      - loadbalancing

  service4:
    build:
      context: ./services/service4/
    image: "nginx-testing-service4:latest"
    container_name: "nginx-testing-service4"
    ports:
      - "8004:5000"
    networks:
      - loadbalancing

  nginx-service:
    build:
      context: ./nginx/
    image: "nginx-testing:latest"
    container_name: "nginx-latest"
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
      - service3
      - service4
    networks:
      - loadbalancing
